FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY midterm_app_login.py /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/midterm_app_login.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY midterm_app_login.py /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/midterm_app_login.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY midterm_app_login.py /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/midterm_app_login.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY midterm_app_login.py /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/midterm_app_login.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY midterm_app_login.py /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/midterm_app_login.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY midterm_app_login.py /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/midterm_app_login.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY midterm_app_login.py /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/midterm_app_login.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY midterm_app_login.py /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/midterm_app_login.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY midterm_app_login.py /home/myapp/
COPY accounts.db /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/midterm_app_login.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY midterm_app_login.py /home/myapp/
COPY accounts.db /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/midterm_app_login.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY midterm_app_login.py /home/myapp/
COPY accounts.db /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/midterm_app_login.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY midterm_app_login.py /home/myapp/
COPY accounts.db /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/midterm_app_login.py
